os:
  - linux
  - osx
sudo: required
language: cpp
compiler:
  - gcc
  - clang
install:
  - make install_deps
  - source setup.bash
script:
  - mkdir build && cd build && cmake .. && make && make test